### ISSUE TITLE
What is the best way to contribute more data?

### ISSUE THREAD

**Issue by ericlewis** [bricklife/LEGO-Mario-Reveng#2]
Do you have a process or how do you capture images? I have more things from scanning with my own Swift lib on this. Just wondering how to contribute!

**Comment by danieldabate** [comment]
Hey Eric! I also started playing with Lego Mario + Swift. 

What extra information did you collect? Unfortunately this repo doesn't seem to get updated with contributions, but maybe you can share it here in the comments to help others.

**Comment by bricklife** [comment]
@ericlewis @danieldabate Thank you for your comments. Sorry, I have not noticed this issue for a long time...

About color barcode, my interest is how to decode/encode it. So I have no plan to collect all barcode data.

**Comment by jeffyjeffy1023** [comment]
Oh! My guess would just b to decode the Start pipe and End flag, then just log what Mario scans. Then, scan each unique code one course at a time, and then just make a list of each code's 0x## hex whatever alongside what things have that code. (e.g. 0x02 - Goomba, Paragoomba)
________________________________
